import { NextRequest, NextResponse } from 'next/server'
import { isDemoMode, getDemoData, getDemoSubroute } from '@/lib/demo-data'
import { getEnginePayload, getWeatherRuntimeHealth, isWeatherEngineEnabled } from '@/lib/weather-engine'

// When WEATHER_ENGINE_ENABLED=1, the two observation payloads are generated by
// this repository's in-process ingestion engine. Every other dashboard payload
// keeps the existing proxy/demo behaviour so no trading or dashboard component
// contract changes are required in this round.
const UPSTREAM_BASE = process.env.UPSTREAM_BASE ?? 'http://localhost:3000'

export const dynamic = 'force-dynamic'

function payloadForType(type: string, search: URLSearchParams): unknown {
  if (type === 'weather-health') return getWeatherRuntimeHealth()
  if (isWeatherEngineEnabled()) {
    const live = getEnginePayload(type)
    if (live !== undefined) return live
  }
  return getDemoData(type, search)
}

export async function GET(req: NextRequest, { params }: { params: { path?: string[] } }) {
  const sub = params.path?.length ? `/${params.path.join('/')}` : ''
  const search = req.nextUrl.searchParams

  // Health is intentionally available even when the observation engine is not
  // enabled; it exposes configuration errors without risking a fake dashboard.
  if (!sub && search.get('type') === 'weather-health') return NextResponse.json(getWeatherRuntimeHealth())

  if (isDemoMode()) {
    if (sub) return NextResponse.json(getDemoSubroute(sub, search))
    const multiTypes = search.get('types')
    if (multiTypes) {
      const out: Record<string, unknown> = {}
      for (const type of multiTypes.split(',').map((value) => value.trim()).filter(Boolean)) out[type] = payloadForType(type, search)
      return NextResponse.json(out)
    }
    const singleType = search.get('type')
    return NextResponse.json(payloadForType(singleType ?? 'weather-intel', search))
  }

  const url = `${UPSTREAM_BASE}/api/brain/trading${sub}${req.nextUrl.search}`
  try {
    const headers: Record<string, string> = { accept: 'application/json' }
    if (process.env.UPSTREAM_SECRET) headers.authorization = `Bearer ${process.env.UPSTREAM_SECRET}`
    const response = await fetch(url, { cache: 'no-store', headers, signal: AbortSignal.timeout(55_000) })
    const body = await response.text()
    return new NextResponse(body, {
      status: response.status,
      headers: { 'content-type': response.headers.get('content-type') ?? 'application/json' },
    })
  } catch (error) {
    return NextResponse.json({ error: `upstream fetch failed: ${String(error)}` }, { status: 502 })
  }
}

export async function POST() {
  return NextResponse.json({ error: 'read-only preview' }, { status: 405 })
}
